GET http://localhost:3000/users

###

GET http://localhost:3000/users/651992faf2915287ea3223d5

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "JohnDoe",
    "email": "John@doe.com",
    "password": "password"
}